Django/dahengduan-working_directory/backend/urls.py
from django.contrib import admin
from django.urls import path, include
import views

urlpatterns = [
    path('tasks/dashboard/', views.dashboard, name='dashboard'),
]

Django/dahengduan-working_directory/comments/urls.py
from django.urls import path

from . import views

app_name = 'comments'
urlpatterns = [
    path('post/', views.post_comment, name='post_comment'),
]

Django/dahengduan-working_directory/django_project/urls.py
from django.contrib import admin
from django.urls import path, include
from mainapp.views import index, ethnic_page, contacts, tourism_page
import allauth
from backend.views import dashboard
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.staticfiles.urls import static
from . import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path('mainapp/', include('mainapp.urls', namespace='mainapp')),
    path('account/', include('allauth.urls')),
    path("", index),
    path("dashboard/", dashboard),
    path("comment/", include('comments.urls', namespace='comments'))
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Django/dahengduan-working_directory/mainapp/urls.py
from django.urls import path
from . import views

app_name = 'mainapp'

urlpatterns = [
    path('index/', views.index, name='index'),
    path('ethnic_page/', views.ethnic_page, name='ethnic_page'),
    path('contacts/', views.contacts, name='contacts'),
    path('tourism_page/', views.tourism_page, name='tourism_page'),
]

Django/dahengduan-working_directory/backend/models.py
from django.db import models

# Create your models here.

Django/dahengduan-working_directory/comments/models.py
from django.db import models
from mptt.models import MPTTModel, TreeForeignKey
from django.contrib.auth.models import User
from mainapp.models import tourism

# Create your models here.


class comment(MPTTModel):
    place = models.ForeignKey(
        tourism,
        on_delete=models.CASCADE
    )
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments'
    )
    content = models.TextField(max_length=140)
    create_time = models.DateTimeField(auto_now_add=True)
    parent = TreeForeignKey(
        'self',
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        related_name='children'
    )

    reply_to = models.ForeignKey(
        User,
        null=True,
        blank=True,
        on_delete=models.CASCADE,
        related_name='replyers'
    )

    class MPTTMeta:
        order_insertion_by = ['create_time']

    def __str__(self):
        return self.content[:20]

Django/dahengduan-working_directory/mainapp/models.py
from django.db import models
from django.db.models.signals import pre_delete, post_init, post_save
from django.dispatch import receiver


# Create your models here.

class pic(models.Model):
    img = models.ImageField(upload_to='img')
    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name



class tourism(models.Model):

    name = models.CharField(max_length=20)
    img = models.ImageField(upload_to='tourism')
    img_index = models.ImageField(upload_to='tourism')
    intro = models.CharField(max_length=250)
    longitude = models.FloatField()
    latitude = models.FloatField()

    def __str__(self):
        return self.name


class ethnic(models.Model):
    name = models.CharField(max_length=20)
    img = models.ImageField(upload_to='ethnic')
    intro = models.CharField(max_length=250)
    population = models.CharField(max_length=20)
    intro_long = models.CharField(max_length=1000)
    def __str__(self):
        return self.name


@receiver(pre_delete, sender=pic)
@receiver(pre_delete, sender=tourism)
@receiver(pre_delete, sender=ethnic)
def file_delete(instance, **kwargs):  # 函数名随意
    # print('进入文件删除方法，删的是',instance.img)   # 用于测试
    instance.img.delete(False)  # file是保存文件或图片的字段名**


@receiver(post_init, sender=pic)
@receiver(post_init, sender=tourism)
@receiver(post_init, sender=ethnic)
def file_path(sender, instance, **kwargs):
    instance._current_file = instance.img


@receiver(post_save, sender=pic)
@receiver(post_save, sender=tourism)
@receiver(post_save, sender=ethnic)
def delete_old_image(sender, instance, **kwargs):
    if hasattr(instance, '_current_file'):
        if instance._current_file != instance.img:
            instance._current_file.delete(save=False)

Django/dahengduan-working_directory/comments/forms.py
from django import forms
from .models import comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = comment
        fields = ['content']

Django/dahengduan-working_directory/backend/views.py
from django.shortcuts import render

# Create your views here.
from django.contrib.auth.models import User
from django.shortcuts import render
from mainapp.models import tourism, ethnic, pic


def dashboard(request):
    user_count = User.objects.count()
    attractions_count = tourism.objects.count()
    ethnics_count = ethnic.objects.count()
    img_count = pic.objects.count()

    context = {'user_count': user_count, 'attactions_count': attractions_count, 'ethnics_count': ethnics_count, 'img_count': img_count}
    return render(request, 'backend/dashboard.html', context)

Django/dahengduan-working_directory/comments/views.py
from django.shortcuts import render, redirect
from django.views.generic.list import ListView
from .models import comment
from mainapp.models import tourism
from .forms import CommentForm


# Create your views here.
def post_comment(request):
    # HTTP 请求有 get 和 post 两种，一般用户通过表单提交数据都是通过 post 请求，
    # 因此只有当用户的请求为 post 时才需要处理表单数据。
    if request.method == 'POST':
        form = CommentForm(request.POST)
        #if form.is_valid():
            # 检查到数据是合法的，调用表单的 save 方法保存数据到数据库，
            # commit=False 的作用是仅仅利用表单的数据生成 Comment 模型类的实例，但还不保存评论数据到数据库。

        user = request.user
        place = tourism.objects.all()[0]
        content = request.POST.get('content')

        comment_temp = comment(user=user, place=place, content=content)
        # 最终将评论数据保存进数据库，调用模型实例的 save 方法
        comment_temp.save()


    return redirect("mainapp:tourism_page")

Django/dahengduan-working_directory/mainapp/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from .models import pic, tourism, ethnic
from comments.models import comment
import json
import markdown
from comments.forms import CommentForm


# Create your views here.
def index(request):
    img = pic.objects.all()
    attractions = tourism.objects.all()
    ethnics = ethnic.objects.all()
    current_user = request.user
    return render(request, 'index.html',
                  {'img': img, 'attractions': attractions, 'ethnic': ethnics, 'user': current_user})


def ethnic_page(request):
    img = pic.objects.all()
    ethnics = ethnic.objects.all()
    current_user = request.user
    return render(request, 'ethnic.html', {'img': img, 'ethnics': ethnics, 'user': current_user})


def contacts(request):
    img = pic.objects.all()
    current_user = request.user
    return render(request, 'contacts.html', {'img': img, 'user': current_user})


def tourism_page(request):
    comment_list = comment.objects.all()
    current_user = request.user
    img = pic.objects.all()
    attractions = tourism.objects.all()
    ethnics = ethnic.objects.all()
    address_longitude = []
    address_latitude = []
    address_data = []
    form = CommentForm()

    for i in range(len(attractions)):
        address_longitude.append(attractions[i].longitude)
        address_latitude.append(attractions[i].latitude)
        address_data.append(attractions[i].intro)

    return render(request, 'tourism.html', {'img': img, 'attractions': attractions, 'ethnic': ethnics,
                                               'address_longitude': json.dumps(address_longitude),
                                               'address_latitude': json.dumps(address_latitude),
                                               'address_data': json.dumps(address_data),
                                               'user': current_user,
                                               'comment_list': comment_list,
                                               'form': form})

Django/dahengduan-working_directory/templates/backend/dashboard.html
<!DOCTYPE html>
<html lang="zh-cn">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>控制面板</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- Theme style -->
    <link rel="stylesheet" href="https://adminlte.io/themes/AdminLTE/bower_components/bootstrap/dist/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://adminlte.io/themes/AdminLTE/dist/css/AdminLTE.min.css">
</head>

<body>
<div class="wrapper">
 <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <!-- Small boxes (Stat box) -->
        <div class="row">
          <div class="col-sm-3">
            <!-- small box -->
            <div class="small-box bg-info">
              <div class="inner">
                <h3>{{ user_count }}</h3>

                <p>用户总数</p>
              </div>
              <div class="icon">
                <i class="ion ion-bag"></i>
              </div>
              <a href="/admin/auth/user/" class="small-box-footer">更多信息 <i class="fas fa-arrow-circle-right"></i></a>
            </div>
          </div>
          <!-- ./col -->
          <div class="col-sm-3">
            <!-- small box -->
            <div class="small-box bg-success">
              <div class="inner">
                <h3>{{ attactions_count }}</h3>
                <p>景点总数</p>
              </div>
              <div class="icon">
                <i class="ion ion-stats-bars"></i>
              </div>
              <a href="/admin/mainapp/tourism/" class="small-box-footer">更多信息 <i class="fas fa-arrow-circle-right"></i></a>
            </div>
          </div>
          <!-- ./col -->
             <div class="col-sm-3">
            <!-- small box -->
            <div class="small-box bg-info">
              <div class="inner">
                <h3>{{ ethnics_count }}</h3>

                <p>民族总数</p>
              </div>
              <div class="icon">
                <i class="ion ion-bag"></i>
              </div>
              <a href="/admin/mainapp/ethnic/" class="small-box-footer">更多信息 <i class="fas fa-arrow-circle-right"></i></a>
            </div>
          </div>
          <!-- ./col -->
          <div class="col-sm-3">
            <!-- small box -->
            <div class="small-box bg-success">
              <div class="inner">
                <h3>{{ img_count }}</h3>

                <p>前台图片总数</p>
              </div>
              <div class="icon">
                <i class="ion ion-stats-bars"></i>
              </div>
              <a href="/admin/mainapp/pic/" class="small-box-footer">更多信息 <i class="fas fa-arrow-circle-right"></i></a>
            </div>
          </div>
          <!-- ./col -->

        </div>
      </div>
    </section>
  </div>
</body> 

Django/dahengduan-working_directory/templates/contacts.html
<!DOCTYPE html>
{% load static %}
<html class="wide wow-animation" lang="en">
  <head>
    <title>Contacts</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, height=device-height, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link rel="icon" href="{% static "images/favicon.ico" %}" type="image/x-icon">
    <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Montserrat:300,400,700%7CPoppins:300,400,500,700,900">
    <link rel="stylesheet" href="{% static "css/bootstrap.css" %}">
    <link rel="stylesheet" href="{% static "css/fonts.css" %}">
    <link rel="stylesheet" href="{% static "css/style.css" %}">
    <style>.ie-panel{display: none;background: #212121;padding: 10px 0;box-shadow: 3px 3px 5px 0 rgba(0,0,0,.3);clear: both;text-align:center;position: relative;z-index: 1;} html.ie-10 .ie-panel, html.lt-ie-10 .ie-panel {display: block;}</style>
  </head>
  <body>
    <div class="ie-panel"><a href="http://windows.microsoft.com/en-US/internet-explorer/"><img src="{% static "images/ie8-panel/warning_bar_0000_us.jpg" %}" height="42" width="820" alt="You are using an outdated browser. For a faster, safer browsing experience, upgrade for free today."></a></div>
    <div class="preloader">
      <div class="preloader-body">
        <div class="cssload-container">
          <div class="cssload-speeding-wheel"></div>
        </div>
        <p>Loading...</p>
      </div>
    </div><a class="section section-banner d-none d-xl-block" href="#" target="_blank" style="background-image: url({% static "images/background-02-1920x60.jpg" %}); background-image: -webkit-image-set( url({% static "images/background-02-1920x60.jpg" %}) 1x, url({% static "images/background-02-3840x120.jpg" %}) 2x )"><img src="{{ MEDIA_URL }}{{ img.1.img }}" srcset="{{ MEDIA_URL }}{{ img.1.img }} 1x, {{ MEDIA_URL }}{{ img.1.img }} 2x" alt="" width="1600" height="310"></a>
    <div class="page">
      <header class="section page-header">
        <!--RD Navbar-->
        <div class="rd-navbar-wrap">
          <nav class="rd-navbar rd-navbar-classic" data-layout="rd-navbar-fixed" data-sm-layout="rd-navbar-fixed" data-md-layout="rd-navbar-fixed" data-md-device-layout="rd-navbar-fixed" data-lg-layout="rd-navbar-static" data-lg-device-layout="rd-navbar-static" data-xl-layout="rd-navbar-static" data-xl-device-layout="rd-navbar-static" data-lg-stick-up-offset="46px" data-xl-stick-up-offset="46px" data-xxl-stick-up-offset="46px" data-lg-stick-up="true" data-xl-stick-up="true" data-xxl-stick-up="true">
            <div class="rd-navbar-collapse-toggle rd-navbar-fixed-element-1" data-rd-navbar-toggle=".rd-navbar-collapse"><span></span></div>
            <div class="rd-navbar-aside-outer rd-navbar-collapse bg-gray-dark">
              <div class="rd-navbar-aside">
                <ul class="list-inline navbar-contact-list">
                  <li>
                    <div class="unit unit-spacing-xs align-items-center">
                      <div class="unit-left"><span class="icon text-middle fa-phone"></span></div>
                      <div class="unit-body"><a href="tel:#">+1 800 123 45 67</a></div>
                    </div>
                  </li>
                  <li>
                    <div class="unit unit-spacing-xs align-items-center">
                      <div class="unit-left"><span class="icon text-middle fa-envelope"></span></div>
                      <div class="unit-body"><a href="mailto:#">info@dahengduan.org</a></div>
                    </div>
                  </li>
                  <li>
                    <div class="unit unit-spacing-xs align-items-center">
                      <div class="unit-left"><span class="icon text-middle fa-map-marker"></span></div>
                      <div class="unit-body"><a href="#">甘肃省兰州市城关区天水南路222号</a></div>
                    </div>
                  </li>
                </ul>
                <ul class="social-links">
                    {% if user.is_authenticated %}
                    <li><a href="#">{{user}}</a></li>
                        <li><a href="{% url 'account_logout' %}">注销</a></li>

                    {% else %}
                        <li><a href="{% url 'account_login' %}">登录</a></li>
                    <li><a href="{% url 'account_signup' %}">注册</a></li>

                    {% endif %}
                </ul>
              </div>
            </div>
            <div class="rd-navbar-main-outer">
              <div class="rd-navbar-main">
                <!--RD Navbar Panel-->
                <div class="rd-navbar-panel">
                  <!--RD Navbar Toggle-->
                  <button class="rd-navbar-toggle" data-rd-navbar-toggle=".rd-navbar-nav-wrap"><span></span></button>
                  <!--RD Navbar Brand-->
                  <div class="rd-navbar-brand">
                    <!--Brand--><a class="brand" href={% url "mainapp:index" %}><img class="brand-logo-dark" src="{% static "images/logo-hengduan-200x34.png" %}" alt="" width="100" height="17"/><img class="brand-logo-light" src="{% static "images/logo-hengduan-200x34.png" %}" alt="" width="100" height="17"/></a>
                  </div>
                </div>
                <div class="rd-navbar-main-element">
                  <div class="rd-navbar-nav-wrap">
                    <ul class="rd-navbar-nav">
                      <li class="rd-nav-item"><a class="rd-nav-link" href={% url "mainapp:index" %}>Home</a>
                      </li>
                      <li class="rd-nav-item"><a class="rd-nav-link" href={% url "mainapp:ethnic_page" %}>Ethnic</a>
                      </li>
                      <li class="rd-nav-item"><a class="rd-nav-link" href={% url "mainapp:tourism_page" %}>Tourism</a>
                      </li>
                      <li class="rd-nav-item active"><a class="rd-nav-link" href={% url "mainapp:contacts" %}>Contacts</a>
                      </li>
                    </ul>
                  </div>
                </div>
              </div>
            </div>
          </nav>
        </div>
      </header>
      <section class="section section-intro context-dark">
        <div class="intro-bg" style="background: url({% static "images/intro-bg-1.jpg" %}) no-repeat;background-size:cover;background-position: top center;"></div>
        <div class="container">
          <div class="row justify-content-center">
            <div class="col-xl-8 text-center">
              <h1 class="font-weight-bold wow fadeInLeft">Contacts</h1>
              <p class="intro-description wow fadeInRight">Ut enim ad minim laboris nisi ut aliquip ex ea commodo consequat.</p>
            </div>
          </div>
        </div>
      </section>
      <!--Mailform-->
      <section class="section section-md">
        <div class="container">
          <!--RD Mailform-->
          <div class="row justify-content-center">
            <div class="col-xl-6 col-md-8 col-12">
              <form class="rd-mailform text-left" data-form-output="form-output-global" data-form-type="contact" method="post" action="bat/rd-mailform.php">
                <div class="form-wrap">
                  <label class="form-label" for="contact-name">Name<span class="req-symbol">*</span></label>
                  <input class="form-input" id="contact-name" type="text" name="name" data-constraints="@Required">
                </div>
                <div class="form-wrap">
                  <label class="form-label" for="contact-phone">Phone<span class="req-symbol">*</span></label>
                  <input class="form-input" id="contact-phone" type="text" name="phone" data-constraints="@Required @PhoneNumber">
                </div>
                <div class="form-wrap">
                  <label class="form-label" for="contact-email">E-Mail<span class="req-symbol">*</span></label>
                  <input class="form-input" id="contact-email" type="email" name="email" data-constraints="@Required @Email">
                </div>
                <div class="form-wrap">
                  <label class="form-label label-textarea" for="contact-message">Message<span class="req-symbol">*</span></label>
                  <textarea class="form-input" id="contact-message" name="message" data-constraints="@Required"></textarea>
                </div>
                <!--Google captcha-->
                <div class="form-wrap text-left form-validation-left">
                  <div class="recaptcha" id="captcha1" data-sitekey="6LfZlSETAAAAAC5VW4R4tQP8Am_to4bM3dddxkEt"></div>
                </div>
                <div class="form-button group-sm text-center text-lg-left">
                  <button class="button button-primary" type="submit">Send</button>
                </div>
              </form>
            </div>
          </div>
        </div>
      </section>
      <a class="section section-banner" target="_blank" style="background-image: url({% static "images/background-01-1920x310.jpg" %}); background-image: -webkit-image-set( url({% static "images/background-01-1920x310.jpg" %}) 1x, url({% static "images/background-01-3840x620.jpg" %}) 2x )"><img src="{{ MEDIA_URL }}{{ img.0.img }}" srcset="{{ MEDIA_URL }}{{ img.0.img }} 1x, {{ MEDIA_URL }}{{ img.0.img }} 2x" alt="" width="1600" height="310"></a>

      <footer class="section footer-classic section-sm">
        <div class="container">
          <div class="row row-30">
            <div class="col-lg-3 wow fadeInLeft">
              <!--Brand--><a class="brand" href="#"><img class="brand-logo-dark" src="{% static "images/logo-hengduan-200x34.png" %}" alt="" width="100" height="17"/><img class="brand-logo-light" src="{% static "images/logo-hengduan-200x34.png" %}" alt="" width="100" height="17"/></a>
              <p class="footer-classic-description offset-top-0 offset-right-25">大横断历史文化研究团队是一个专门研究历史文化的学术团队，致力于探讨历史与文化之间的关系，并运用现代研究方法对历史和文化进行研究。该团队的研究领域包括：历史文化、文化遗产、历史地理、文化人类学等。</p>
            </div>
            <div class="col-lg-3 col-sm-8 wow fadeInUp">
              <P class="footer-classic-title">contact info</P>
              <div class="d-block offset-top-0">甘肃省兰州市城关区<span class="d-lg-block">天水南路222号</span></div><a class="d-inline-block accent-link" href="#">info@dahengduan.org</a><a class="d-inline-block" href="#">+1 800 123 45 67</a>
              <ul>
                <li>工作日:<span class="d-inline-block offset-left-10 text-white">9:30 AM - 9:00 PM</span></li>
                <li>周六:<span class="d-inline-block offset-left-10 text-white">10:00 AM - 9:00 PM</span></li>
                <li>周日:<span class="d-inline-block offset-left-10 text-white">10:00 AM - 3:00 PM</span></li>
              </ul>
            </div>
            <div class="col-lg-2 col-sm-4 wow fadeInUp" data-wow-delay=".3s">
              <P class="footer-classic-title">Quick Links</P>
              <ul class="footer-classic-nav-list">
                <li><a href="{% url 'mainapp:index' %}">Home</a></li>
                <li><a href="{% url 'mainapp:index' %}">About us</a></li>
                <li><a href="#">Services</a></li>
                <li><a href="#">Blog</a></li>
                <li><a href="{% url 'mainapp:contacts' %}">Contacts</a></li>
              </ul>
            </div>

          </div>
        </div>

      </footer>
    </div>
    <div class="snackbars" id="form-output-global"></div>
    <script src="{% static "js/core.min.js" %}"></script>
    <script src="{% static "js/script.js" %}"></script>
  </body>
</html>